crud_demo/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("user/login", views.user_login, name="user_login"),
    path("user/logout", views.user_logout, name="user_logout"),
    path("user/<int:user_id>/books", views.books_list, name="books_list"),
    path("user/<int:user_id>/book_add", views.book_add, name="book_add"),
    path("user/<int:user_id>/book/edit/<int:book_id>", views.book_edit, name="book_edit"),
    path("user/<int:user_id>/book/delete/<int:book_id>", views.book_remove, name="book_remove")
]

python_learning/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("crud_demo/", include(("crud_demo.urls", "crud_demo"), namespace="crud_demo"))
    # path('admin/', admin.site.urls),
]

crud_demo/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
    
class Book(models.Model):
    user   = models.ForeignKey(User, on_delete=models.CASCADE) 
    name   = models.CharField(max_length=200)
    author = models.CharField(max_length=200)

crud_demo/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .models import Book
from django.urls import reverse
# Create your views here.
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username = username, password = password)
        if user:
            if user.is_active:
                login(request, user)
                messages.success(request, "login successfully...!")
                return HttpResponseRedirect('%d/books'%user.id)
        else:
            messages.error(request, "Invalid username/password")
            return render(request, "crud_demo/user/login.html")        
    else:
        return render(request, "crud_demo/user/login.html")

def user_logout(request):
    logout(request)
    messages.success(request, "logout successfully...!")
    return HttpResponseRedirect(reverse("crud_demo:user_login"))

@login_required(login_url = "crud_demo:user_login")
def books_list(request, user_id):
    books = Book.objects.filter(user_id = user_id)
    context = {
        "books": books,
        "user_id": user_id
    }
    return render(request, "crud_demo/book/index.html", context)

@login_required(login_url = "crud_demo:user_login")
def book_add(request, user_id):
    context = {
        "user_id": user_id
    }
    if request.method == 'POST':
        book_name   = request.POST.get("book_name")
        author_name = request.POST.get("author_name")
        book = Book(name = book_name, author = author_name, user_id = user_id)
        book.save()
        messages.success(request, "Book created successfully...!")
        return HttpResponseRedirect(reverse("crud_demo:books_list", args = (user_id,)))
    else:
        return render(request, "crud_demo/book/create.html", context)

@login_required(login_url = "crud_demo:user_login")
def book_edit(request, user_id, book_id):
    book = load_book(user_id, book_id)
    context = {"book": book, "user_id": user_id}
    if request.method == 'POST':
        book.name   = request.POST.get("book_name")
        book.author = request.POST.get("author_name")
        book.save()
        messages.success(request, "Book updated successfully...!")
        return HttpResponseRedirect(reverse("crud_demo:books_list", args = (user_id,)))
    else:
        return render(request, "crud_demo/book/edit.html", context)

@login_required(login_url = "crud_demo:user_login")    
def book_remove(request, user_id, book_id):
    book = load_book(user_id, book_id)
    book.delete() 
    messages.success(request, "Book deleted successfully...!")
    return HttpResponseRedirect(reverse("crud_demo:books_list", args = (user_id,)))
    
def load_book(user_id, book_id):
    return Book.objects.filter(user_id = user_id, id = book_id).first()

crud_demo/templates/crud_demo/book/create.html
{% load static %}
<html>
  <head>
    <link rel="stylesheet" href="{% static 'css/book/create.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>
  <body>
    {%include 'crud_demo/book/header.html'%}
    <div class="container">
      <h1><b> Add Book </b><h1>
      <form action="{%url 'crud_demo:book_add' user_id%}" method="POST">{% csrf_token %}
        <label>Name</label>
        <input type="text" class="form-control" name="book_name" required=true style="width:30%">
        <label>Author</label>
        <input type="text" class="form-control" name="author_name" style="width:30%">
        <button type="submit" class="btn btn-success" style="margin-top:10px">Submit</button>
        <a href="{%url 'crud_demo:books_list' user_id%}" class="btn btn-info" style="margin-top:10px">Back</a>
      </form>
    </div>
  </body>
</html>

crud_demo/templates/crud_demo/book/edit.html
<html>
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>
  <body>
    {%include 'crud_demo/book/header.html'%}
    <div class="container">
      <h1><b> Edit Book </b><h1>
      <form action="{%url 'crud_demo:book_edit' user_id book.id%}" method="POST">{% csrf_token %}
        <label>Name</label>
        <input type="text" class="form-control" name="book_name" value="{{book.name}}" required=true style="width:30%">
        <label for="uname"><b>Author</b></label>
        <input type="text" class="form-control" name="author_name" value="{{book.author}}" style="width:30%">
        <button type="submit" class="btn btn-success" style="margin-top:10px">Submit</button>
        <a href="{%url 'crud_demo:books_list' user_id%}" class="btn btn-info" style="margin-top:10px">Back</a>
      </form>
    </div>
  </body>
</html>

crud_demo/templates/crud_demo/book/header.html
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Crud Demo</a>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="{%url 'crud_demo:user_logout'%}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
    </ul>
  </div>
</nav>

crud_demo/templates/crud_demo/book/index.html
{% load static %}
<html>
  <head>
    <link rel="stylesheet" href="{% static 'css/book/index.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  </head>
  <body>
    {%include 'crud_demo/book/header.html'%}
    {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'success'%}
                <script>M.toast({html: "{{message}}", classes: 'green rounded', displayLength:2000});</script>
            {% elif message.tags == 'error'%}
                <script>M.toast({html: "{{message}}", classes: 'red rounded', displayLength:10000});</script>
            {% endif %}
        {% endfor %}
    {% endif %}
    <div class="container">
      <h1><b>Books</b></h1>
      <form>
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Name</th>
              <th>Author</th>
              <th>
                <a href="{% url 'crud_demo:book_add' user_id%}" class="add_book" data-toggle="tooltip" data-placement="bottom" title="Add book">
                  <span class="glyphicon glyphicon-plus"></span>
                </a>
              </th>
            </tr>
          </thead>
          <tbody>
            {%for book in books%}
            <tr>
              <td>{{book.name}}</td>
              <td>{{book.author}}</td>
              <td>
                <a href="{% url 'crud_demo:book_edit' user_id book.id%}" class="add_book" data-toggle="tooltip" data-placement="bottom" title="Edit book">
                  <span class="glyphicon glyphicon-edit"></span>
                </a>
              </td>
              <td>
                <a href="{% url 'crud_demo:book_remove' user_id book.id%}" class="add_book" data-toggle="tooltip" data-placement="bottom" title="Delete book">
                  <span class="glyphicon glyphicon-remove"></span>
                </a>
              </td>
            </tr>
            {%endfor%}
          </tbody>
        </table>
      <form>
    </div>
  </body>
</html>

crud_demo/templates/crud_demo/user/login.html
{% load static %}
<html>
  <head>
    <link rel="stylesheet" href="{% static 'css/user/login.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>
  <body>
    {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'success'%}
                <script>M.toast({html: "{{message}}", classes: 'green rounded', displayLength:3000});</script>
            {% elif message.tags == 'error'%}
                <script>M.toast({html: "{{message}}", classes: 'red rounded', displayLength:3000});</script>
            {% endif %}
        {% endfor %}
    {% endif %}
    <form action="{%url 'crud_demo:user_login'%}" method="POST">{% csrf_token %}
      <div class="container log_form" style="background-color:#333;width:50%;padding-bottom: 10px;margin-top: 15%; border-radius:10px">
        <h1 class="login_header" style="color:white">Sign In</h1>
        <label for="uname" style="color:white"><b>Username</b></label>
        <input type="text" class="form-control" name="username">
        
        <label for="uname" style="color:white"><b>Password</b></label>
        <input type="password" class="form-control" name="password">

        <button type="submit" class="btn btn-success" style="margin:auto;display:block;margin-top: 10px;">Sign In</button>
      </div>
    </form>
  </body>
</html>